/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class backendinterface_BEinterface */

#ifndef _Included_backendinterface_BEinterface
#define _Included_backendinterface_BEinterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     backendinterface_BEinterface
 * Method:    updatePositions
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_backendinterface_BEinterface_updatePositions
  (JNIEnv *, jobject);

/*
 * Class:     backendinterface_BEinterface
 * Method:    getCommunitites
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_backendinterface_BEinterface_getCommunitites
  (JNIEnv *, jobject);

/*
 * Class:     backendinterface_BEinterface
 * Method:    getClusterColors
 * Signature: ()[[F
 */
JNIEXPORT jobjectArray JNICALL Java_backendinterface_BEinterface_getClusterColors
  (JNIEnv *, jobject);

/*
 * Class:     backendinterface_BEinterface
 * Method:    getEdges
 * Signature: ()[Lbackendinterface/Edge;
 */
JNIEXPORT jobjectArray JNICALL Java_backendinterface_BEinterface_getEdges
  (JNIEnv *, jobject);

/*
 * Class:     backendinterface_BEinterface
 * Method:    getPositions
 * Signature: ()[Lbackendinterface/Point;
 */
JNIEXPORT jobjectArray JNICALL Java_backendinterface_BEinterface_getPositions
  (JNIEnv *, jobject);

/*
 * Class:     backendinterface_BEinterface
 * Method:    startsProgram
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_backendinterface_BEinterface_startsProgram
  (JNIEnv *, jobject, jstring);

/*
 * Class:     backendinterface_BEinterface
 * Method:    freeAllocatedMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_backendinterface_BEinterface_freeAllocatedMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
